#For configuring Locust script
[locust run]
host: 
locustfile: materialorder.py

#For Headless Execution
[headless mode]
headless: true
users: 2
hatch-rate: 1
run-time: 20s
--html: report.html



