#For configuring Locust script
[locust script]
locustfile: materialorder.py
host: 

#For configuring worker mode
[locust worker mode]
worker: true
master-host: 127.0.0.1
master-port: 5557

